#!/bin/bash

# https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract
mode=$1;shift 1;

while [ "$#" -gt 0 ]; do
  case "$1" in
    --lang) lang="$2"; shift 2;;
    --font) font="$2"; shift 2;;
    --exp) exp="exp$2"; shift 2;;
    --image) image="$2"; shift 2;;
    -*) echo "unknown option: $1" >&2; exit 1;;
    *) echo "unknown option: $1" >&2; exit 1;;
  esac
done

font="${font:-$lang}"
exp="${exp:-exp0}"

resource_path="/vagrant/${lang}"
training_path="/home/vagrant/tesseract-3.03.02/training"

prefix="${lang}.${font}.${exp}"
prefix_with_path="${resource_path}/${prefix}"

echo $prefix_with_path
echo "$TESSDATA_PREFIX"


if [ "$mode" == "box" ]
then
  echo "Creating box for $prefix"
  sudo tesseract "${prefix_with_path}.tif" "${prefix_with_path}" batch.nochop makebox
  echo "${prefix_with_path}.box created"
elif [ "$mode" == "train" ]
then
  echo "Start training for $prefix"
  # train with your box file
  tesseract "${prefix_with_path}.tif" "${prefix_with_path}" box.train.stderr


  # put all font that you want to be included for the language
  # <fontname> <italic> <bold> <fixed> <serif> <fraktur>
  touch "${font}_font_properties"
  echo "${font} 0 0 0 0 0" > "${font}_font_properties"
  sudo mv "${font}_font_properties" $training_path

  # change into training directory
  cd $training_path

  # make unicharset
  sudo ./unicharset_extractor "${prefix_with_path}.box" # lang.fontname.exp1.box ...

  # i don't know what this does
  # set_unicharset_properties -U input_unicharset -O output_unicharset --script_dir=training/langdata

  # make shapetable
  sudo ./shapeclustering -F "${font}_font_properties" -U unicharset "${prefix_with_path}.tr"

  # creates inttemp (the shape prototypes) 
  # creates pffmtable (the number of expected features for each character)
  # Microfeat is also written by this program, but it is not used
  sudo ./mftraining -F "${font}_font_properties" -U unicharset -O "${lang}.unicharset" "${prefix_with_path}.tr" 

  # creates normproto
  sudo ./cntraining "${prefix_with_path}.tr" # lang.fontname.exp1.tr ...

  pffmtable="${lang}.pffmtable"
  inttemp="${lang}.inttemp"
  shapetable="${lang}.shapetable"
  normproto="${lang}.normproto"

  # rename files to prepend language.
  sudo mv pffmtable "${pffmtable}"
  sudo mv inttemp "${inttemp}"
  sudo mv shapetable "${shapetable}"
  sudo mv normproto "${normproto}"
  sudo ./combine_tessdata "${lang}."

  cur_time=`date +%s`
  bak_dir="${prefix_with_path}_traindata-${cur_time}"
  mkdir $bak_dir
  sudo cp "${lang}.traineddata" "${font}_font_properties" $pffmtable $inttemp $shapetable $normproto $bak_dir

  echo "Created training data in ${training_path} and backed up to ${bak_dir}"

  sudo cp "${lang}.traineddata" $TESSDATA_PREFIX
  echo "Copied ${lang}.traineddata to ${TESSDATA_PREFIX}"
elif [ "$mode" == "test" ]
then
  echo "Testing ${lang}"
  #test
  cd $resource_path
  if [ -z "$image" ]
  then
    echo "traineract test --image PATH_TO_IMAGE --lang"
  else
    cur_time=`date +%s`
    out_path="${resource_path}/${lang}.test.${cur_time}"
    tesseract "${image}" "${out_path}" -l $lang

    echo "Generated output at ${out_path}.txt"
  fi
else
  echo "usage: traineract [box|train|test] --lang LANG_NAME"
  echo "traineract [box|train|test] --font FONT_NAME --lang LANG_NAME"
  echo "traineract [box|train|test] --font FONT_NAME --lang LANG_NAME --exp NUM"
fi
